on:
  push:

name: generate executables

jobs:
  linux:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v2.3.1
        with:
          path: asb
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax

      - name: test python
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel
          pip install -r asb/requirements.txt

      # - name: install dependencies
      #   run: |
      #     python3 -m pip install --upgrade pip setuptools wheel
      #     pip3 install -r asb/requirements.txt
      #     export PATH="$PATH:/home/runner/.local/bin"

      - name: build
        run: |
          pyinstaller --onefile asb/asb.py

      - name: copy
        run: |
          rm -rf ./asb/dist/linux
          mkdir -p ./asb/dist/linux
          mv ./dist/asb ./asb/dist/linux/asb

  # macos:
  #   name: macos
  #   runs-on: macos-latest
  #   steps:
  #     - name: check out code
  #       uses: actions/checkout@v2.3.1
  #       with:
  #         path: asb
  #         fetch-depth: 0

  #     - name: install dependencies
  #       run: |
  #         pip install -r asb/requirements.txt

  #     - name: build
  #       run: |
  #         echo "I am the macosx builder"

  # windows:
  #   name: windows
  #   runs-on: windows-latest
  #   steps:
  #     - name: check out code
  #       uses: actions/checkout@v2.3.1
  #       with:
  #         path: asb
  #         fetch-depth: 0

  #     - name: install dependencies
  #       run: |
  #         pip install -r asb/requirements.txt

  #     - name: build
  #       run: |
  #         echo "I am the windows builder"
